import { StyleSheet } from 'react-native';

export const getStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.text,
    marginLeft: 15,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  emptyText: {
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 40,
    fontSize: 16,
  },
  manageCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    padding: 15,
    borderRadius: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  manageIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: `${colors.primary}15`,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  manageInfoBox: {
    flex: 1,
  },
  manageName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  manageType: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  dateSelectorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  dateSelectorTextContainer: {
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 10,
  },
  dateSelectorText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    width: 150,
    textAlign: 'center',
  },
  dateSelectorBtn: {
    padding: 10,
    backgroundColor: colors.surface,
    borderRadius: 12,
  },
  submitCard: {
    backgroundColor: colors.surface,
    padding: 15,
    borderRadius: 20,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  submitHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  submitInputsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  inputWrapper: {
    flex: 1,
  },
  inputLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    marginBottom: 6,
    marginLeft: 4,
  },
  meterInput: {
    backgroundColor: colors.background,
    color: colors.text,
    padding: 12,
    borderRadius: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  commentInput: {
    backgroundColor: colors.background,
    color: colors.text,
    padding: 15,
    borderRadius: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.outline,
    minHeight: 100,
    textAlignVertical: 'top',
    marginTop: 15,
  },
  formSubmitBtn: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 20,
    marginTop: 10,
    marginBottom: 40,
  },
  formSubmitBtnText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },

  /* --- СТИЛІ БЛОКУ ФОТОГРАФІЇ --- */
  photoSectionContainer: {
    marginBottom: 5,
  },
  photoUploadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  photoUploadingText: {
    color: colors.textSecondary,
    marginTop: 10,
  },
  photoPreviewContainer: {
    alignItems: 'center',
  },
  photoPreviewImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    marginBottom: 10,
  },
  photoDeleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.dangerSoft,
    padding: 10,
    borderRadius: 8,
  },
  photoDeleteText: {
    color: colors.danger,
    marginLeft: 5,
    fontWeight: '600',
  },
  photoAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: `${colors.primary}30`,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${colors.primary}30`,
    borderStyle: 'dashed',
  },
  photoAddText: {
    color: colors.primary,
    marginLeft: 10,
    fontWeight: '600',
    fontSize: 16,
  },
});